#pragma once

#define MONSTER_BOARD_KEY_TARGETACTOR TEXT("TargetActor")
#define MONSTER_BOARD_KEY_TARGETPOS TEXT("TargetPos")
#define MONSTER_BOARD_KEY_PATROLPOS TEXT("PatrolPos")
#define MONSTER_BOARD_KEY_HOMEPOS TEXT("HomePos")
#define MONSTER_BOARD_KEY_ISATTACKED TEXT("IsAttacked")
